see

diff --git a/.github/workflows/testing.yaml b/.github/workflows/testing.yaml
--- a/.github/workflows/testing.yaml
+++ b/.github/workflows/testing.yaml
@@ -38,6 +38,13 @@ jobs:
         dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --package=.
       working-directory: cos301_capstone
 
+    - name: Check if lcov.info exists
+      run: |
+        if [ ! -f cos301_capstone/coverage/lcov.info ]; then
+          echo "lcov.info file not found"
+          exit 1
+        fi
+
     - name: Code Coverage Summary
       uses: irongut/CodeCoverageSummary@v1.3.0
       with:
@@ -73,6 +80,9 @@ jobs:
     - name: List Lighthouse Results Directory
       run: ls -la ./lighthouse-results
 
+    - name: Print results.json for Debugging
+      run: cat ./lighthouse-results/results.json
+
     - name: Extract Performance Score
       id: extract_score
       run: |
@@ -82,7 +92,7 @@ jobs:
             exit 1
         fi
 
-        SCORE=$(jq '.categories.performance.score * 100' "$REPORT_FILE")
+        SCORE=$(jq '.[0].categories.performance.score * 100' "$REPORT_FILE")
         echo "PERFORMANCE_SCORE=${SCORE%.*}" >> $GITHUB_ENV
 
     - name: Update README with Lighthouse Badge
